name: lbnenvdev
channels:
  - conda-forge
dependencies:
  - python>=3.12
  - osmnx>=2
  - tqdm
  - geojson

  # additional to the non-dev env
  - ipykernel
  - ipywidgets
  - pytest
  - pytest-mpl
  - pytest-cov
  - sphinx
  - numpydoc
  - myst-nb
  - pre-commit
  - jupyterlab
  - pixi-kernel
  - growbikenet
  - pip:
      # not available via conda-forge:
      - sphinx-copybutton
      - furo