name: lbnenvdev
channels:
  - conda-forge
dependencies:
  - python=3.12
  - jupyter
  - jupyterlab
  - ipywidgets
  - ipykernel
  - matplotlib
  - geopandas>=0.14
  - osmnx>=1.9.4
  - pip
  - pytest
  - pixi-pycharm
  - pre-commit
  - sphinx
  - numpydoc
  - myst-nb
  - sphinx-book-theme
  - nbsphinx
  - myst-parser
  - ipython
  - pip:
      # not available via conda-forge:
      - opencv-python
      - pre-commit
      - sphinxcontrib-bibtex
      - sphinx-copybutton
      - sphinx-gallery
      - python-slugify
      - furo