[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "linkbikenet"
version = "0.7.2"
authors = [
  { name = "Manuel Knepper" },
  { name = "Michael Szell" },
]
maintainers = [
    { name = "Michael Szell", email = "michael@szell.net"},
    { name = "Manuel Knepper", email = "manuel.knepper@gmx.net" },
]
license = "AGPL-3.0-or-later"
readme = "README.md"
description = "BikeNetKit Python package to link disconnected bicycle network components"
keywords = ["Bicycle network planning", "Networks", "OpenStreetMap", "Urban Planning", "Urban Mobility"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Natural Language :: English",
]
requires-python = ">=3.10"
dependencies = [
    "geopandas>=1",
    "matplotlib",
    "osmnx>=2",
    "geojson",
    "numpy",
]

[project.urls]
Homepage = "https://bikenetkit.org/linkbikenet/"
Documentation = "https://docs.bikenetkit.org/LinkBikeNet/"
Repository = "https://github.com/BikeNetKit/LinkBikeNet/"
Issues = "https://github.com/BikeNetKit/LinkBikeNet/issues/"
Changelog = "https://docs.bikenetkit.org/LinkBikeNet/changelog/"

[project.optional-dependencies]
test = ["pytest"]
doc = ["sphinx"]

[tool.ruff.lint.extend-per-file-ignores]
"__init__.py" = ["F401"]  # "Imported but unused: happens with packages

[tool.ruff.lint.pydocstyle]
convention = "numpy"

[tool.setuptools.packages.find]
exclude = [
    "examples*",
    "tests*",
    "results",
    "docs*",
    "data*",
    "scripts*",
]
namespaces = false